<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SubscriptionsArticleIds</name>
   <tag></tag>
   <elementGuidId>74e95fb9-4ddc-4ce7-9b9f-b206a2790212</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='assets-form--subscriptions-article-ids-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='assets-form--subscriptions-article-ids-input']</value>
   </webElementProperties>
</WebElementEntity>
