<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GCustomerServicePhoneOrlando</name>
   <tag></tag>
   <elementGuidId>887f006e-ccce-4416-91b2-cf4cc09ca929</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='assets-form-g_customer_service_phone_orlando-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='assets-form-g_customer_service_phone_orlando-input']</value>
   </webElementProperties>
</WebElementEntity>
