<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GCustomerServicePhoneCloud</name>
   <tag></tag>
   <elementGuidId>a74750d1-6790-4b83-9439-23e885774b36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='assets-form-g_customer_service_phone_cloud-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='assets-form-g_customer_service_phone_cloud-input']</value>
   </webElementProperties>
</WebElementEntity>
