<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GEmailContentLocation</name>
   <tag></tag>
   <elementGuidId>0b57fdd5-2391-4a52-8c58-bb5e2a6bad3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='assets-form-g_email_content_location-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='assets-form-g_email_content_location-input']</value>
   </webElementProperties>
</WebElementEntity>
