<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GOutMapLinkTest</name>
   <tag></tag>
   <elementGuidId>9cd9d8a2-d997-4704-86e8-88ae841613d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='assets-form-g_out_map_link_test-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='assets-form-g_out_map_link_test-input']</value>
   </webElementProperties>
</WebElementEntity>
