<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GOutMapLink</name>
   <tag></tag>
   <elementGuidId>0cd81a74-0744-4f59-b772-326ef6920165</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='assets-form-g_out_map_link-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='assets-form-g_out_map_link-input']</value>
   </webElementProperties>
</WebElementEntity>
