<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectEnvironmentQA</name>
   <tag></tag>
   <elementGuidId>01899c16-3143-4435-b343-518813204373</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@id='menu-item-1-menu-item-qa']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[@id='menu-item-1-menu-item-qa']</value>
   </webElementProperties>
</WebElementEntity>
