<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectEnvironmentTest</name>
   <tag></tag>
   <elementGuidId>cf408d4a-9ee8-443f-aa0b-05ab95d1ed0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@id='menu-item-1-menu-item-test']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[@id='menu-item-1-menu-item-test']</value>
   </webElementProperties>
</WebElementEntity>
