<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectEnvironmentDevelop</name>
   <tag></tag>
   <elementGuidId>b54ec477-506c-4e26-8ea6-065a57126102</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@id='menu-item-0-menu-item-develop']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[@id='menu-item-0-menu-item-develop']</value>
   </webElementProperties>
</WebElementEntity>
