<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ChooseAccount</name>
   <tag></tag>
   <elementGuidId>c14ea15d-328f-425e-ac55-64ef25dd7868</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;view_container&quot;)/form[@class=&quot;RFjuSb bxPAYd k6Zj8d&quot;]/div[@class=&quot;mbekbe bxPAYd&quot;]/div[@class=&quot;iUe6Pd Us7fWe JhUD8d&quot;]/div[@class=&quot;RCum0c&quot;]/div[@class=&quot;IqKdAd bxPAYd&quot;]/ul[@class=&quot;sIznTe pggQ5e&quot;]/li[@class=&quot;C5uAFc w6VTHd&quot;]/div[@class=&quot;TnvOCe k6Zj8d XraQ3b&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-profileindex</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TnvOCe k6Zj8d XraQ3b</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>n1UuX</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-authuser</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
</WebElementEntity>
