<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LogInButton</name>
   <tag></tag>
   <elementGuidId>872c9c44-ec9f-4b25-9013-afef87baab51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>button.auth0-lock-submit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>button.auth0-lock-submit</value>
   </webElementProperties>
</WebElementEntity>
