<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LoginButtonNoGoogle</name>
   <tag></tag>
   <elementGuidId>ed14efa5-3d45-430b-95e3-cad96fd3266b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>button.auth0-lock-submit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>button.auth0-lock-submit</value>
   </webElementProperties>
</WebElementEntity>
