<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PRStatus</name>
   <tag></tag>
   <elementGuidId>f62b5629-1f0c-4828-aea2-0d643b54bcf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='root']/div/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/span/div/span[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/span/div/span[4]</value>
   </webElementProperties>
</WebElementEntity>
