<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ContactPausedPreviewLink</name>
   <tag></tag>
   <elementGuidId>48f5fed9-ae7f-4d73-bca8-77715c082199</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@id='blob-contact-paused-njk']//span[@class='templates-list-preview'][contains(text(),'Preview')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[@id='blob-contact-paused-njk']//span[@class='templates-list-preview'][contains(text(),'Preview')]</value>
   </webElementProperties>
</WebElementEntity>
