<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ElectOutage_OutActiveForm</name>
   <tag></tag>
   <elementGuidId>e8dc6e02-4466-4a14-bea8-e53a190d3cfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@id='blob-out-active-njk']//span[@class='template-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[@id='blob-out-active-njk']//span[@class='template-name']</value>
   </webElementProperties>
</WebElementEntity>
