<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ExpandHistory</name>
   <tag></tag>
   <elementGuidId>03938537-d18c-4862-9c16-fdcb3af7f574</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='root']/div/div/div/div[2]/div[2]/div/div[3]/div/div[2]/div/div[2]/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div[2]/div/div[3]/div/div[2]/div/div[2]/div/div/span</value>
   </webElementProperties>
</WebElementEntity>
