<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WaterOutage_WaterRestoredForm</name>
   <tag></tag>
   <elementGuidId>efc281dc-4fb9-4468-8fa1-1f5b7e275ea8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@id='blob-water-restored-njk']//div[@role='presentation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[@id='blob-water-restored-njk']//div[@role='presentation']</value>
   </webElementProperties>
</WebElementEntity>
