<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CommitMessageUnderHistory</name>
   <tag></tag>
   <elementGuidId>2b3ccb72-809f-4082-80f1-e42ed440651c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='root']/div/div/div/div[2]/div[2]/div/div[3]/div/div/div[2]/div/div/div[2]/div/div[2]/div/table/tbody/tr/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div[2]/div/div[3]/div/div/div[2]/div/div/div[2]/div/div[2]/div/table/tbody/tr/td[3]</value>
   </webElementProperties>
</WebElementEntity>
