<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CollapseWhitespaceField</name>
   <tag></tag>
   <elementGuidId>6e659010-3862-4e63-b3b2-242141e48107</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='mappings-form-collapse-whitespace-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='mappings-form-collapse-whitespace-input']</value>
   </webElementProperties>
</WebElementEntity>
