<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PreserveImportantField</name>
   <tag></tag>
   <elementGuidId>00faa741-57e7-46ee-8cda-932bfcc48cb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='mappings-form-preserve-important-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='mappings-form-preserve-important-input']</value>
   </webElementProperties>
</WebElementEntity>
