<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PostingRegistrationAffirmationForm</name>
   <tag></tag>
   <elementGuidId>51c02a0a-b35b-420d-bdee-b54caaeff883</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@id='blob-posting-registration-affirmation-njk']//div[@role='presentation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[@id='blob-posting-registration-affirmation-njk']//div[@role='presentation']</value>
   </webElementProperties>
</WebElementEntity>
