<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PostingContactConfirmedForm</name>
   <tag></tag>
   <elementGuidId>596c6032-816f-4201-b9e2-6133a28806ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@id='blob-posting-contact-confirmed-njk']//div[@role='presentation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[@id='blob-posting-contact-confirmed-njk']//div[@role='presentation']</value>
   </webElementProperties>
</WebElementEntity>
