<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Textbox</name>
   <tag></tag>
   <elementGuidId>c7552858-ab06-4a83-9adb-15b7dbea58c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@role='presentation']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='root']//div[@class='app']/div[@class='route-content']//form//div[@class='CodeMirror-scroll']/div[@class='CodeMirror-sizer']/div/div[@role='presentation']/div[@role='presentation']/div[@role='presentation']//pre[@role='presentation']/span[@role='presentation']</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//pre[@role='presentation']/span[@role='presentation']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//div[@id='root']//div[@class='app']/div[@class='route-content']//form//div[@class='CodeMirror-scroll']/div[@class='CodeMirror-sizer']/div/div[@role='presentation']/div[@role='presentation']/div[@role='presentation']//pre[@role='presentation']/span[@role='presentation']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value></value>
   </webElementXpaths>
</WebElementEntity>
