<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VoiceOptionReportOutageForm</name>
   <tag></tag>
   <elementGuidId>4804db92-b52e-4010-bba5-c87ec2e50d9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@id='blob-voice-option-report-outage-njk']//div[@role='presentation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[@id='blob-voice-option-report-outage-njk']//div[@role='presentation']</value>
   </webElementProperties>
</WebElementEntity>
