<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VoiceDisenrolledForm</name>
   <tag></tag>
   <elementGuidId>4cb6c482-524c-4827-a32d-21ccecce0cb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@id='blob-voice-disenrolled-njk']//div[@role='presentation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[@id='blob-voice-disenrolled-njk']//div[@role='presentation']</value>
   </webElementProperties>
</WebElementEntity>
