<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VoiceDisenrolledPreviewLink</name>
   <tag></tag>
   <elementGuidId>8989fb8e-5e0b-4acc-bbf9-f795ed9e2151</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@id='blob-voice-disenrolled-njk']//span[@class='templates-list-preview'][contains(text(),'Preview')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[@id='blob-voice-disenrolled-njk']//span[@class='templates-list-preview'][contains(text(),'Preview')]</value>
   </webElementProperties>
</WebElementEntity>
