<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VoiceNoInputForm</name>
   <tag></tag>
   <elementGuidId>b73f155b-c407-4eb8-b426-61d715e4b3f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@id='blob-voice-no-input-njk']//div[@role='presentation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[@id='blob-voice-no-input-njk']//div[@role='presentation']</value>
   </webElementProperties>
</WebElementEntity>
